name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  pull_request:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set this secret in your repo settings
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set this secret in your repo settings

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # This points to the root of the repository where the Dockerfile is located
          file: ./Dockerfile  # Path to your Dockerfile
          push: true
          tags: your_dockerhub_username/your_image_name:latest  # Change this to your Docker Hub repository name

      - name: Logout from Docker Hub
        run: docker logout